### ISSUE TITLE
Enforce variable declaration using var

### ISSUE THREAD

**Issue by fischer1983** [enofex/taikai#71]
I think it can be shoud be a good feature.

**Comment by mnhock** [comment]
Using ArchUnit to check for the usage of var in Java is not feasible directly since var is a feature of the Java language syntax and not something that is represented distinctly in the bytecode. When the Java compiler processes var declarations, it infers the type and converts them into explicit type declarations in the bytecode, making it impossible for bytecode analysis tools like ArchUnit to detect them.
