### ISSUE TITLE
failOnEmpty failing

### ISSUE THREAD

**Issue by erikpragt-connectid** [enofex/taikai#81]
Hi there, just wondering if I might do something wrong, but I'm my understanding of `failOnEmpty` was that the test should fail if it cannot find any matching classes. 

I've enabled that here in my demo application: https://github.com/erikpragt-connectid/taikai-issue/blob/main/src/test/java/au/com/connectid/taikaidemo/ArchitectureTest.java#L18 

But when I enable it, I'm getting an error:

```
Rule 'classes that have only static methods should be final and should have a private constructor' failed to check any classes. This means either that no classes have been passed to the rule at all, or that no classes passed to the rule matched the `that()` clause. To allow rules being evaluated without checking any classes you can either use `ArchRule.allowEmptyShould(true)` on a single rule or set the configuration property `archRule.failOnEmptyShould = false` to change the behavior globally.
```

If I disable it, and I make a typo in my package name, the tests pass. I'd like to prevent that from happening. 

Am I missing something here?

Cheers,

Erik

**Comment by mnhock** [comment]
Hi @erikpragt-connectid ,

The issue you're facing with the failOnEmpty configuration in your ArchUnit test seems to stem from how the rules are defined and applied. When the failOnEmpty option is enabled, it expects to find at least one class that matches the rule criteria. If no classes are found, it results in an error as you've described. So in my opinion it is working here correct.

Here’s what you can check and adjust to ensure your tests fail correctly when no matching classes are found:

Ensure the Package Path is Correct: Verify that the package path provided in your tests matches the actual package structure of your classes. This is crucial because a typo or mismatch here would result in no classes being found, triggering the failOnEmpty error.

failOnEmpty  is set in Taikai globally this behavior across all rules. Per rule is at the moment not possible. But when you use custom rules (https://github.com/enofex/taikai/blob/main/docs/USERGUIDE.md#adding-custom-archunit-rules)  you are able to do this per rule.

**Comment by erikpragt-connectid** [comment]
Hi @mnhock , thanks for the explanation. 

The reason why I reported this issue is that my test configuration was passing, but what I didn't notice, was that I had a space in my package name. Therefore, no code matched, and no offending rules were broken. Is there any suggested approach to prevent this? I've now replaced the package name by `.namespace(MyApplicationClass.class.getPackageName())`, but even that isn't super safe since if someone moves that `MyApplicationClass` to a different package, it might stop scanning the right packages. 

Is there any recommended way to make sure at least a certain amount of code is scanned?

**Comment by mnhock** [comment]
I am not aware of any possibilities in ArchUnit, but maybe this can be one idea:

```
@Test
void shouldImportClasses() {
        JavaClasses importedClasses = new ClassFileImporter().importPackages(YOUR.BASE_PACKAGE);
        assertThat(importedClasses).isNotEmpty(); // Ensure that classes are being scanned
}
```
